// src/components/MilestonesBox.jsx
import { useEffect, useState } from "react";
import { listMilestones, createMilestone, deleteMilestone } from "../api/milestones";

export default function MilestonesBox({ projectId, canEdit = false }) {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [name, setName] = useState("");
  const [target, setTarget] = useState("");

  const load = async () => {
    setLoading(true);
    try {
      const data = await listMilestones(projectId);
      setItems(Array.isArray(data) ? data : []);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, [projectId]);

  /* ===================== Actions ===================== */
  const add = async () => {
    if (!target || Number(target) <= 0) return;

    await createMilestone(projectId, {
      name: name || undefined,
      targetAmount: Number(target),
    });

    setName("");
    setTarget("");
    load();
  };

  const remove = async (id) => {
    if (!window.confirm("Excluir milestone?")) return;
    await deleteMilestone(projectId, id);
    load();
  };

  /* ===================== Render ===================== */
  return (
    <div className="panel">
      <h3 className="text-base font-semibold mb-3">🎯 Marcos do projeto</h3>

      {loading && <div className="text-muted">Carregando…</div>}

      {!loading && items.length === 0 && (
        <div className="text-muted">Nenhum milestone ainda.</div>
      )}

      <ul className="space-y-2">
        {items
          .sort((a, b) => a.order - b.order)
          .map((m) => {
            const completed = m.completed;
            const auto = m.autoGenerated;

            return (
              <li
                key={m.id}
                className={`flex items-center justify-between rounded-md border px-3 py-2 text-sm
                  ${completed
                    ? "bg-emerald-50 border-emerald-200 text-emerald-900"
                    : "bg-white border-black/10"}
                `}
              >
                {/* Left */}
                <div className="flex items-center gap-2">
                  <span className="text-lg">
                    {completed ? "✅" : "⏳"}
                  </span>

                  <div>
                    <div
                      className={`font-medium ${
                        completed ? "line-through opacity-80" : ""
                      }`}
                    >
                      {m.name}
                    </div>

                    <div className="text-xs opacity-70">
                      Alvo: {m.targetAmount.toLocaleString("pt-BR")} palavras
                    </div>
                  </div>
                </div>

                {/* Right */}
                <div className="flex items-center gap-2">
                  {auto ? (
                    <span className="px-2 py-0.5 text-xs rounded-full bg-blue-100 text-blue-800">
                      🤖 automático
                    </span>
                  ) : (
                    <span className="px-2 py-0.5 text-xs rounded-full bg-slate-100 text-slate-700">
                      ✍️ manual
                    </span>
                  )}

                  {canEdit && !auto && (
                    <button
                      onClick={() => remove(m.id)}
                      className="text-xs text-red-600 hover:underline"
                    >
                      Excluir
                    </button>
                  )}
                </div>
              </li>
            );
          })}
      </ul>

      {/* ===== Criar milestone manual ===== */}
      {canEdit && (
        <div className="mt-4 border-t pt-3">
          <div className="text-sm font-medium mb-2">
            Criar milestone manual
          </div>

          <div className="flex gap-2">
            <input
              className="input"
              placeholder="Nome (opcional)"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <input
              className="input w-32"
              type="number"
              placeholder="Alvo"
              value={target}
              onChange={(e) => setTarget(e.target.value)}
            />
            <button className="btn-primary" onClick={add}>
              Adicionar
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
